### ISSUE TITLE
safe_yaml warning

### ISSUE THREAD

**Issue by lamont-granquist** [PhilT/app_conf#1]
getting a lot of this warning banner from knife-spork which uses the app_conf gem:

```
Called 'load_file' without the :safe option -- defaulting to safe mode.
You can avoid this warning in the future by setting the SafeYAML::OPTIONS[:default_mode] option (to :safe or :unsafe).
```

**Comment by juliandunn** [comment]
Heads up @jonlives

**Comment by jonlives** [comment]
Hmm, first time I've seen that occuring with knife-spork... @lamont-granquist what version of app_conf are you using?

**Comment by juliandunn** [comment]
@jonlives I also see the problem, and I'm on app_conf 0.4.1

I think this call needs to be changed: https://github.com/PhilT/app_conf/blob/master/lib/app_conf.rb#L10

**Comment by jonlives** [comment]
Ah fair enough - @PhilT would you be able to fix this please?

**Comment by PhilT** [comment]
Wow! People are using this! Sure no problem. I'll try to take a look at this shortly.

**Comment by jonlives** [comment]
@PhilT don't be surprised, it's an awesome Gem :)

**Comment by PhilT** [comment]
0.4.2 gem is now up. Gave up trying to write an automated test - too much hassle - but it's just a config option and I've added a check before setting it so should be fine.

Let me know if it fixes the issue or not.

Cheers,
Phil

**Comment by lamont-granquist** [comment]
:+1:
